### ISSUE TITLE
Caret won't display, even after setting prop to true

### ISSUE THREAD

**Issue by 698373862** [vueform/multiselect#158] opened 2021-10-21 12:52 UTC
I have got multiselect component with prop `:canDeselect="true"`, whenever I have this on true, I can't see the caret svg icon. When I set `caret="true"` it doesn't appear as well. Why am I not seeing the caret even though I set the prop to true?

**Comment by nick-barth** [comment] 2021-11-22 10:29
Which version are you using?

**Comment by adamberecz** [comment] 2021-12-16 07:49
Make sure to include background images in `tailwind.config.js`:
https://github.com/vueform/multiselect#styling-with-tailwind-css

As I couldn't reproduce the issue I'm closing this for now. If it persists feel free to reopen with a reproducible example.

**Closed by adamberecz** 2021-12-16 07:49 UTC
