### ISSUE TITLE
css file is not imported

### ISSUE THREAD

**Issue by uzaneran** [vueform/multiselect#325] opened 2023-03-22 14:22 UTC
Hi,
I have a vue-3 app using vueform-multiselect and it looks like there's an issue with the css file import
![image](https://user-images.githubusercontent.com/17277577/226933792-5f34fb8c-3abf-4eb2-b59a-d3a9f1384f56.png)

In another computer of mine it works properly

I don't know how it's possible.

thanks,
Eran.

**Comment by arrocke** [comment] 2023-03-29 15:49
We are seeing this as well on version 2.6.1. Version 2.6.0 does not have the issue. I suspect it is due to the addition of the exports field in package.json. Trying to reproduce in codesandbox right now

**Comment by Fli-c** [comment] 2023-04-10 10:51
I believe the cause is [sideEffects](https://webpack.js.org/guides/tree-shaking/) flag,
https://github.com/vueform/multiselect/blob/e3ca5e649a9bcbd53555d7ee1cfa47be3808bc12/package.json#L37
It can be overridden in local package.json like this
```json5
...
module: {
    rules: [
        ...,
        {
            include: path.resolve('node_modules', '@vueform', 'multiselect'),
            sideEffects: true,
        },
    ],
},
```
Although this will disable webpacks "tree shaking" feature completely. Ideally it should be an array of paths to component css files, but IDE tells me that webpack expects just boolean value here. It'll do for now I guess 🤷‍♂️

**Comment by adamberecz** [comment] 2023-10-06 14:41
We no longer have `sideEffects: false`, so closing this.

**Closed by adamberecz** 2023-10-06 14:41 UTC
