### ISSUE TITLE
All options selected when I open the dropdown

### ISSUE THREAD

**Issue by carmolim** [vueform/multiselect#155] opened 2021-10-14 23:56 UTC
Hello! I'm having some problems, I'm using @vueform/multiselect": "^2.2.0" with "vue": "^2.6.11",  and this multiselect:
```
<Multiselect
    placeholder="Select your report"
    mode="single"
    :closeOnSelect="true"
    :searchable="true"
    :options="dashboards"
    label="title"
    trackBy="title"
    :object="true"
/> 
```
My options are like this:
```
[
  {
    id: 3,
    title: "Report 1",
    queryInfo: {
      start: 1634153936332,
      end: 1634240336332,
      dimensions: [],
      metrics: [],
      filters: []
    }
  }
  ...
]
```
The problem is that when I open the multiselect all the options are already selected, what I'm missing?

![Screen Shot 2021-10-14 at 20 40 56](https://user-images.githubusercontent.com/2863161/137410954-13855ddc-56c7-4531-97b2-4de6f21f0ab3.png)

**Comment by carmolim** [comment] 2021-10-15 11:47
I tried that here: https://jsfiddle.net/carmolim/2mog5j7f/2/, but didn't fix it.

**Comment by carmolim** [comment] 2021-10-15 19:56
That worked for me too, but I can't change the id to value.. I'm getting this data from an API, anything else I could do?

**Comment by tntsoft** [comment] 2021-11-29 14:22
@adamberecz Any news on this?

I see there was a release 6 days ago, but this wasn't tackled.

**Comment by adamberecz** [comment] 2021-12-16 06:48
It seems like the issue was in the fiddle example, `valueProp` should be `value-prop`. When using plain HTML to define components always remember that attribute names are being converted to lowercase. Here's the fixed version:
https://jsfiddle.net/fy3g5m1d/

I think in your initial example what you were missing was the `v-model`:
```vue
<Multiselect
    v-model="value"
    placeholder="Select your report"
    mode="single"
    :closeOnSelect="true"
    :searchable="true"
    :options="dashboards"
    label="title"
    trackBy="title"
    :object="true"
/> 
```

Closing this as I couldn't reproduce any errors. If you still think there's an issue feel free to reopen.

**Closed by adamberecz** 2021-12-16 06:48 UTC
